### ISSUE TITLE
Import user error after installing this plug-in

### ISSUE THREAD

**Issue by JSOMTC-KM** [rezaies/moodle-profilefield_file#1]
I have a Moodle instance (v2.8.3+) to which I've installed this plug-in. When I try to import a new group of users I get a very generic error and the import fails with a invalid user error and link to the moodle "error/moodle/invaliduser" page which doesn't explain anything.
![invalid user error](https://cloud.githubusercontent.com/assets/11229378/6412722/abb24e22-be55-11e4-94d2-fada51b8bae7.PNG)

**Comment by JSOMTC-KM** [comment]
Now I'm having issues removing this plug-in

**Comment by JSOMTC-KM** [comment]
Had to edit the mdl_config_plugins database entry for this plugin (delete) after removing the plugin directory from the application directory

**Comment by rezaies** [comment]
Thanks for reporting this.
1. can you please upload a sample user files? I tested it myself ad it was fine. What columns does your file have?
2. You probably cannot remove the plugin because you have defined one or more associated profile fields. You should be able to uninstall the plugin if you remove those custom profile fields.

**Comment by rezaies** [comment]
You are right. There is a bug somewhere. I'll fix it soon. Thanks again for your report and sorry for any inconvenience this may have caused.

**Comment by rezaies** [comment]
fixed. please download the new code from github and give it a try now.
